### ISSUE TITLE
Problem with node timers (mesecon button for example)

### ISSUE THREAD

**Issue by pyrollo** [thomasrudin-mt/jumpdrive#23]
When using a mesecon button to trigger jumpdrive, once jumped, the mesecon button stays in "pressed" state. I guess this is due to node timer not referring to the old position.

Easy way to solve this would be to transform mesecons_button:button_on into mesecons_button:button_off when jumping.

Best way would be to find a way to "move" node timers.

**Comment by thomasrudin** [comment]
If only there were a function for this like with the meta:

> minetest.find_nodes_with_meta(pos1, pos2)
https://github.com/minetest/minetest/blob/1c91cb8f8f6ea15dc1308aace666bd1ebd25a28c/doc/lua_api.txt#L3869

I rewrote my meta-move code with this function and halfed the time it took for a jump

Something like
> minetest.find_nodes_with_timers(pos1, pos2)

Otherwise the lookup is iterative and pretty time-consuming

**Comment by thomasrudin** [comment]
Hybrid solution:
Check and copy node-timers of:
* node-whitelist (blinkyplant, etc)
* nodes with meta (find_nodes_with_meta)

**Comment by pyrollo** [comment]
To build the whitelist, you can use a minetest.after fuction that populates it with all nodes having a "on_timer" attribute.
